package com.cbt.main.model;

public class Dictionaries {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.id
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.name
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.upidid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String upidid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.upname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String upname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.type
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.areaid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.areaname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.eid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionaries.ename
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String ename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.id
     *
     * @return the value of dictionaries.id
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.id
     *
     * @param id the value for dictionaries.id
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.name
     *
     * @return the value of dictionaries.name
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.name
     *
     * @param name the value for dictionaries.name
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.upidid
     *
     * @return the value of dictionaries.upidid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getUpidid() {
        return upidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.upidid
     *
     * @param upidid the value for dictionaries.upidid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setUpidid(String upidid) {
        this.upidid = upidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.upname
     *
     * @return the value of dictionaries.upname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getUpname() {
        return upname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.upname
     *
     * @param upname the value for dictionaries.upname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setUpname(String upname) {
        this.upname = upname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.type
     *
     * @return the value of dictionaries.type
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.type
     *
     * @param type the value for dictionaries.type
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.areaid
     *
     * @return the value of dictionaries.areaid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.areaid
     *
     * @param areaid the value for dictionaries.areaid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.areaname
     *
     * @return the value of dictionaries.areaname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.areaname
     *
     * @param areaname the value for dictionaries.areaname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.eid
     *
     * @return the value of dictionaries.eid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.eid
     *
     * @param eid the value for dictionaries.eid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setEid(String eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionaries.ename
     *
     * @return the value of dictionaries.ename
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionaries.ename
     *
     * @param ename the value for dictionaries.ename
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setEname(String ename) {
        this.ename = ename;
    }
}