package com.cbt.main.model;

import java.io.Serializable;
import java.util.Date;

public class MessageCount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agricultural.iid
     *
     * @mbggenerated Thu Nov 10 19:24:02 CST 2016
     */
    private String c1;

    private String c2;
    
    private String c3;

	public String getC1() {
		return c1;
	}

	public String getC2() {
		return c2;
	}

	public String getC3() {
		return c3;
	}
    
    
}