package com.cbt.main.model;

import java.io.Serializable;

public class Usercrop implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.cid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.cname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.ctid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String ctid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.ctname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String ctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.uid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.p1
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String p1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.p2
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String p2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.p3
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String p3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.p4
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String p4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercrop.p5
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    private String p5;

    public Usercrop()
    {

    }

    public Usercrop(String cid,String cname,String ctid,String ctname)
    {
        this.cid = cid;
        this.cname = cname;
        this.ctid = ctid;
        this.ctname = ctname;
        this.p1 = "";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.cid
     *
     * @return the value of usercrop.cid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.cid
     *
     * @param cid the value for usercrop.cid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.cname
     *
     * @return the value of usercrop.cname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.cname
     *
     * @param cname the value for usercrop.cname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.ctid
     *
     * @return the value of usercrop.ctid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getCtid() {
        return ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.ctid
     *
     * @param ctid the value for usercrop.ctid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setCtid(String ctid) {
        this.ctid = ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.ctname
     *
     * @return the value of usercrop.ctname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getCtname() {
        return ctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.ctname
     *
     * @param ctname the value for usercrop.ctname
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setCtname(String ctname) {
        this.ctname = ctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.uid
     *
     * @return the value of usercrop.uid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.uid
     *
     * @param uid the value for usercrop.uid
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.p1
     *
     * @return the value of usercrop.p1
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getP1() {
        return p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.p1
     *
     * @param p1 the value for usercrop.p1
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setP1(String p1) {
        this.p1 = p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.p2
     *
     * @return the value of usercrop.p2
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getP2() {
        return p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.p2
     *
     * @param p2 the value for usercrop.p2
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setP2(String p2) {
        this.p2 = p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.p3
     *
     * @return the value of usercrop.p3
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getP3() {
        return p3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.p3
     *
     * @param p3 the value for usercrop.p3
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setP3(String p3) {
        this.p3 = p3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.p4
     *
     * @return the value of usercrop.p4
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getP4() {
        return p4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.p4
     *
     * @param p4 the value for usercrop.p4
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setP4(String p4) {
        this.p4 = p4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercrop.p5
     *
     * @return the value of usercrop.p5
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public String getP5() {
        return p5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercrop.p5
     *
     * @param p5 the value for usercrop.p5
     *
     * @mbggenerated Tue Nov 08 10:50:22 CST 2016
     */
    public void setP5(String p5) {
        this.p5 = p5;
    }
}