package com.cbt.main.model;

import java.io.Serializable;
import java.util.List;

public class ZaiqingBigModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agricultural.iid
     *
     * @mbggenerated Thu Nov 10 19:24:02 CST 2016
     */
    private List<ZaiqingModel> nongqinglist;

    private MessageCount mscount;

	public List<ZaiqingModel> getNongqinglist() {
		return nongqinglist;
	}

	public void setNongqinglist(List<ZaiqingModel> nongqinglist) {
		this.nongqinglist = nongqinglist;
	}

	public MessageCount getMscount() {
		return mscount;
	}

	public void setMscount(MessageCount mscount) {
		this.mscount = mscount;
	}
    
    
}